aws_region        = "us-east-2"
project_name      = "secscan-minimal-prod"
container_image   = "public.ecr.aws/nginx/nginx:latest"
container_port    = 80
use_https         = true
acm_certificate_arn = "" # fill when ready
health_check_path = "/"
nat_strategy      = "per_az"
allowed_cidrs     = ["0.0.0.0/0"]
